Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/08/2024
Var
Birula, baralho: real


Inicio
escreval ("Informe um numero de 0 a 10")
leia (Birula)
enquanto Birula <> baralho faca
baralho <- randi (10)
escreval (baralho)
fimenquanto





Fimalgoritmo